server:
  port: 8070
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

masterAddresses:
  - "http://localhost:8000"
  - "http://localhost:8001"
  - "http://localhost:8002"